### PR TITLE
[Gateway] : Gateway Version on footer of the page along with styling fixes

### LINKED ISSUE #551: [gateway] introduce gateway version in the footer of the page
## Issue Type

```
[ ] bug report
[x] feature request
```

## Current Behavior
We don't exactly know which version of the gateway we're looking at.

## Expected Behavior
Show version of the project `"version": "0.0.3",` and make sure it gets bumped in releases.

## Steps to Reproduce

1.
2.
3.

## Suggested Fix
Show gateway version in the footer

### LINKED ISSUE #574: Enable Gas fee view on mobile

### PR DESCRIPTION
**Pull request by sk-enya**
:clipboard: Add associated issues, tickets, docs URL here.

## Overview
1. Pick the version from the package.json automatically while preparing build.
2. Fix the footer styling.
3. Enable Gas Fees on the mobile screen

## Changes
- Added gateway version on the page footer
- Style fixes for the footer on mobile and desktop screen

## Testing
Just update the version details in a package.json of the gateway to show it on UI.

The app version will be visible on the footer on rebuilding the app with the 
Screenshot 2023-02-09 at 11 48 11 PM
Screenshot 2023-02-09 at 11 48 29 PM
script `yarn build or yarn dev`. ref screenshot.

### CODE REVIEW

**Comment by boyuan-chen** [comment]
Could you please update everything related to `checkVersion` in `packages/boba/gateway/src/actions/serviceAction.js`? Since we are going to use a global env for it.

**Comment by sk-enya** [comment]
> Could you please update everything related to `checkVersion` in `packages/boba/gateway/src/actions/serviceAction.js`? Since we are going to use a global env for it.

Sure let me look into it.

**Comment by sk-enya** [comment]
@Boyuan-Chen can you please help me here? is this automated? or do we manually update it whenever a version of the web wallet/gateway is published?

https://github.com/bobanetwork/boba/blob/develop/ops_boba/api/service-api/webwallet_version.py#L17

**Comment by boyuan-chen** [comment]
> @Boyuan-Chen can you please help me here? is this automated? or do we manually update it whenever a version of the web wallet/gateway is published?
> 
> https://github.com/bobanetwork/boba/blob/develop/ops_boba/api/service-api/webwallet_version.py#L17

This API is invalid! The cache is controlled in Cloudfront.

**Comment by boyuan-chen** [comment]
I removed the API files.

**Review by boyuan-chen — APPROVED** [review]

**Comment by sk-enya** [comment]
@Boyuan-Chen, Thank you, I also did a cleanup on the gateway as the wallet version api is removed.

**Comment by InoMurko** [comment]
this is great. how is `npm_package_version` controlled?

**Review by InoMurko — APPROVED** [review]

**Comment by sk-enya** [comment]
> this is great. how is `npm_package_version` controlled?

@InoMurko 
**package.json vars**
Actually The package.json fields are tacked onto the _npm_package__ prefix. So, for instance, if you had {"name":"foo", "version":"1.2.5"} in your package.json file, then your package scripts would have the npm_package_name environment variable set to "foo", and the npm_package_version set to "1.2.5". we can easily access these variables in code with process.env.npm_package_name and process.env.npm_package_version, and for other fields as well.

**Pull request merged**
