### PR TITLE
Update turing tests mainnet

### PR DESCRIPTION
**Pull request by CAPtheorem**
https://github.com/omgnetwork/optimism-v2/pull/458

adds new mainnet addresses for Turing contracts

### CODE REVIEW

**Comment by InoMurko** [comment]
@wsdt ideas with this PR?

**Comment by wsdt** [comment]
@InoMurko Haven't seen this yet, but looks good to me. basically just adding the specific contract addresses for Boba and the credit contract to the example tests. 

I think we could merge this.

**Comment by InoMurko** [comment]
And the addresses are valid?

**Comment by wsdt** [comment]
yes they are

**Review by InoMurko — APPROVED** [review]

**Comment by InoMurko** [comment]
Pls approve 😁

**Review by wsdt — APPROVED** [review]

**Review by souradeep-das — APPROVED** [review]

**Pull request merged**
