### PR TITLE
Deploy ETH to BNB Testnet L2

### PR DESCRIPTION
**Pull request by boyuan-chen**
:clipboard: Add associated issues, tickets, docs URL here.

## Overview

Describe what your Pull Request is about in a few sentences.

Deploy ETH on BNB Testnet L1 and L2

## Changes

Describe your changes and implementation choices. More details make PRs easier to review.

- Add ETH to our list 

## Testing

Describe how to test your new feature/bug fix and if possible, a step by step guide on how to demo this.

### CODE REVIEW

**Comment by boyuan-chen** [comment]
@sk-enya we need add this token to gateway

**Review by wsdt — APPROVED** [review]

**Comment by souradeep-das** [comment]
where is the testnet eth on bnb testnet sourced from? or do we deploy a dummy token?

**Comment by wsdt** [comment]
Looks like a dummy token. 

> where is the testnet eth on bnb testnet sourced from? or do we deploy a dummy token?

**Comment by InoMurko** [comment]
https://testnet.bscscan.com/token/0xd66c6b4f0be8ce5b39d52e0fd1344c389929b378
https://testnet.bnbchain.org/faucet-smart

**Comment by souradeep-das** [comment]
yeah i think we should use this - "0xd66c6B4F0be8CE5b39D52E0Fd1344c389929B378" (if we can) instead of the dummy token

**Comment by souradeep-das** [comment]
PS - this would also need a new TK_L2 in that case before merge

**Comment by wsdt** [comment]
> PS - this would also need a new TK_L2 in that case before merge

@Boyuan-Chen thank you!

**Comment by boyuan-chen** [comment]
The new L2 token is deployed to https://blockexplorer.testnet.bnb.boba.network/address/0xc614A66f82e71758Fa7735C91dAD1088c8362f15/read-contract#address-tabs

**Review by souradeep-das — APPROVED** [review]

**Pull request merged**
