### PR TITLE
[Gateway] : Status alert for BobaBeam

### LINKED ISSUE #728: When switching to Moonbeam <> Bobabeam chain a banner should appear
Bobabeam is closing - please withdraw your funds

### LINKED ISSUE #730: Disable *Deposit* button on Bobabeam

### LINKED ISSUE #731: gateway: url with wrong params failing redirect to ethereum if wrong values.

### LINKED ISSUE #735: Unit test setup with jest & react testing library + code coverage for gateway.

### PR DESCRIPTION
**Pull request by sk-enya**
:clipboard: Add associated issues, tickets, docs URL here.

closes: https://github.com/bobanetwork/boba/issues/730
closes: https://github.com/bobanetwork/boba/issues/728
closes: https://github.com/bobanetwork/boba/issues/731

## Overview

Show banner as we are closing BobaBeam and disable deposit to boba beam.

## Changes

Describe your changes and implementation choices. More details make PRs easier to review.

- Add a theme for styled components with sizes & breakpoints.
- Created a `NotificationBar` component to show banner, prepared with styled-component, themes and responsive.
- Added show more and less for content on notification banner.
- Disabled the deposit on Moonbeam `Classic bridge, Fast bridge`. ref screenshot below.
- Fix for crash on random values for query parameters of `network` and `chain` set the default to `Mainnet & ETHEREUM`.
- Added unit test cases for notification banner.

## Testing

Please refer screenshot below.
## Notification for `closing Bobabeam.`

Screenshot 2023-04-25 at 5 36 08 AM
Screenshot 2023-04-25 at 5 36 13 AM

## Deposit Disable
Screenshot 2023-04-25 at 3 26 48 PM

### CODE REVIEW

**Review by boyuan-chen — APPROVED** [review]

**Comment by InoMurko** [comment]
Please fix the typo in the title of the PR

**Comment by InoMurko** [comment]
@sk-enya could we make the button NOT disabled, but just a slow transition from disabled to enabled-like 3-5 seconds. And alt text appear on hover that Bobabeam is going to be turned off?

**Comment by sk-enya** [comment]
> @sk-enya could we make the button NOT disabled, but just a slow transition from disabled to enabled-like 3-5 seconds. And alt text appear on hover that Bobabeam is going to be turned off?

You mean to say deposit to boba beam?

**Comment by InoMurko** [comment]
Yes

**Review by alvaro-ricotta — APPROVED** [review]

**Pull request merged**
