### PR TITLE
[Gateway] : Add memes wallet to Ecosystem

### PR DESCRIPTION
**Pull request by headria**
## Overview
Add Memes wallet (Planet memes coin) to the list of projects on the Boba Ecosystem page.

## Changes
Add PMC logo in PNG format
Add Memes wallet to the project list

### CODE REVIEW

**Comment by headria** [comment]
Hi, whats the next step ?

**Comment by headria** [comment]
Any update ?

**Review by InoMurko — APPROVED** [review]

**Review by sk-enya — APPROVED** [review]

**Comment by headria** [comment]
hi, any update there?

**Review by boyuan-chen — APPROVED** [review]

**Comment by boyuan-chen** [comment]
> hi, any update there?

Merged!

**Pull request merged**
