### PR TITLE
add aa-paymaster docs

### PR DESCRIPTION
**Pull request by souradeep-das**
:clipboard: https://github.com/bobanetwork/boba/pull/489

## Overview

Add account-abstraction paymaster docs

## Changes

/

## Testing

/

### CODE REVIEW

**Review by wsdt — APPROVED** [review]
love it!

**Review by boyuan-chen — APPROVED** [review]
LGTM

**Comment by InoMurko** [comment]
Good to merge?

**Comment by souradeep-das** [comment]
lets merge this!

**Pull request merged**
