### PR TITLE
Add a new API in DTL for querying status of DTL

### PR DESCRIPTION
**Pull request by boyuan-chen**
## Problem
`/eth/syncing` returns the syncing status, but the design for this allows the replica to sync up before dtl loads all l2 data. Therefore, the `syncing` always returns `false` for l2geth.

## How to solve
This PR introduces the new api endpoint `/eth/syncing/l2`. This returns the actual syncing status, so we can query the actual `highest l2 block` that needs to be synced and current transaction index that dtl has synced.

### CODE REVIEW

**Review by InoMurko — APPROVED** [review]

**Comment by InoMurko** [comment]
does this need reviews and PR template @Boyuan-Chen ?

**Comment by boyuan-chen** [comment]
> does this need reviews and PR template @Boyuan-Chen ?

I edited the PR comments.

**Review by InoMurko — APPROVED** [review]
Lgtm

**Review by wsdt — APPROVED** [review]
looks good to me!

**Pull request merged**
