### PR TITLE
Add dev tool page and TX builder

### PR DESCRIPTION
**Pull request by boyuan-chen**
:clipboard: Add associated issues, tickets, docs URL here.

## Overview

Describe what your Pull Request is about in a few sentences.

- Add a dev tool page for us to add some tools that help developers
- Add TX builder

## Changes

Describe your changes and implementation choices. More details make PRs easier to review.

- Add a new input box
- Add a nice page

### View parameters
image
  
### Failure and successful transactions
image

### CODE REVIEW

**Review by sk-enya — APPROVED** [review]
Looks good to me!

**Comment by InoMurko** [comment]
Forgot to review this but - I would rather put this section in the footer. For most users, this isn't their focus.

**Comment by boyuan-chen** [comment]
> Forgot to review this but - I would rather put this section in the footer. For most users, this isn't their focus.

Sound goo! Done!

**Review by InoMurko — APPROVED** [review]
awesomeeee

**Pull request merged**
