### PR TITLE
[Gateway] : Add GhostNColors  to boba ecosystem 

### PR DESCRIPTION
**Pull request by henrique1837**
:clipboard: Add associated issues, tickets, docs URL here.

## Overview

I would like to add GhostNColors project please

## Changes

- Updated project.list.js
- Added project logo

## Testing

Dapp can be tested at https://ghostncolors-crypto.ipns.dweb.link/   or   https://ghostncolors.on.fleek.co/

### CODE REVIEW

**Comment by boyuan-chen** [comment]
Hi @henrique1837, do you have an official website? Is the NFT listed somewhere?

**Comment by henrique1837** [comment]
Hi I the oficial website is https://ghostncolors-crypto.ipns.dweb.link/   (ghostncolors.crypto)
It is listed in shibuinft only https://shibuinft.com/app/collection/0x51b449D8bc3b46D7b897B5fD0211eAe48c9D7FCA .
I still need to submit to review in other marketplaces.
Thank you

**Comment by sk-enya** [comment]
@henrique1837 can you please resolved the conflict and update the PR please.

**Comment by henrique1837** [comment]
Done thanks. The nft collection has been verified at tofunft https://tofunft.com/collection/ghostncolors

**Review by sk-enya — APPROVED** [review]
LGTM

**Review by InoMurko — APPROVED** [review]

**Comment by InoMurko** [comment]
@sk-enya can you pls resolve the conflicts and merge? thanks

**Comment by sk-enya** [comment]
closing as added this changes to https://github.com/bobanetwork/boba/pull/522

**Pull request closed without merging**
