### PR TITLE
Additional Turing Example: KYC

### PR DESCRIPTION
**Pull request by wsdt**
Public NPM package for contracts dedicated to Boba (e.g. access modifiers for KYC, etc.). 

Added now to monorepo to stay consistent with the overall project structure. 

Happy for feedback.

### CODE REVIEW

**Comment by InoMurko** [comment]
what is `boba/public-contracts`? is this part of our L2 stack or should this go into `boba_examples`? and if it's part of our stack, why not `boba/contracts`?

**Comment by wsdt** [comment]
> what is `boba/public-contracts`? is this part of our L2 stack or should this go into `boba_examples`? and if it's part of our stack, why not `boba/contracts`?

Yes it's thought to be part of the L2 stack as uniform public npm package for the community (e.g. the KYC modifier, etc.). 

Thus, I created the public-contracts folder, as the regular contracts are rather for our internal use or for documentation purposes, cross references etc. and the public contracts folder get's packaged to an own npm package (now on Github packages, but as soon as I get the approval to create a public npm account also for npmjs). 

What's your thought on this?

**Comment by InoMurko** [comment]
For the community as in - for the developer ecosystem? So this is more like an SDK? If it's more like a turing SDK, or a general Boba SDK it makes more sense to name it that way?

**Comment by InoMurko** [comment]
Oh and if it's SDK, then it needs to be tied back into our core services so that it's tested. Or examples need to be turned into tests.

**Comment by wsdt** [comment]
Ok sure, there is an examples folder, what if I move this to `boba/boba_community/sdk-examples` and the folder here in the packages is named as `boba-sdk`?

**Comment by InoMurko** [comment]
Sounds great @wsdt

**Comment by wsdt** [comment]
Done @InoMurko

**Comment by InoMurko** [comment]
ok so now the contracts are part of the sdk package. good, but they need to part of our l2 stack, otherwise they're examples of using turing and should be moved into examples. That's why I asked if they're part of our L2 stack. Where are they being used? or where are they supposed to be used?

**Comment by wsdt** [comment]
> ok so now the contracts are part of the sdk package. good, but they need to part of our l2 stack, otherwise they're examples of using turing and should be moved into examples. That's why I asked if they're part of our L2 stack. Where are they being used? or where are they supposed to be used?

They are actually supposed to be used as modifiers generically on any smart contract on L2. Ok so you want me to move the examples folder to `[boba](https://github.com/bobanetwork/boba/tree/boba-npm)/boba_examples/` ?

**Review by souradeep-das — APPROVED** [review]
looks nice!

**Review by InoMurko — APPROVED** [review]

**Review by CAPtheorem — APPROVED** [review]

**Pull request merged**
