### PR TITLE
Wsdt/turing complex types

### PR DESCRIPTION
**Pull request by wsdt**
Made a simple example for more complex types returned by Turing. 

Please wait with the merge, until @mmontour1306 has merged his Geth changes, otherwise this won't work.

### CODE REVIEW

**Comment by souradeep-das** [comment]
amazing 🎉  should this live under boba_examples?

**Comment by wsdt** [comment]
> amazing 🎉 should this live under boba_examples?

I think so, or what would you recommend? :-)

**Comment by souradeep-das** [comment]
> I think so, or what would you recommend? :-)

yes please, lets move it to boba_examples

**Comment by wsdt** [comment]
> > I think so, or what would you recommend? :-)
> 
> yes please, lets move it to boba_examples

ah I thought you meant the community examples. Yeah both feel correct to me. But I'll move it now.

**Review by souradeep-das — APPROVED** [review]
thanks! looks great!

**Review by InoMurko — APPROVED** [review]
wohooo

**Pull request merged**
