### PR TITLE
Add Bobaopera Testnet docs

### PR DESCRIPTION
**Pull request by boyuan-chen**
## Why we need this?

We deployed on Bobaopera, so need to add docs for it.

## Overview

Add Bobaopera Testnet docs and a file that contains all registered contract addresses

## Changes

- Add Bobaopera Testnet URLs and links
- Add a file that contains all registered contract addresses

### CODE REVIEW

**Review by InoMurko — COMMENTED** [review]
Do you still have the artifacts of the deployment? Please upload them too in the repo. Ignore if you have :)

**Comment by boyuan-chen** [comment]
> Do you still have the artifacts of the deployment? Please upload them too in the repo. Ignore if you have :)

I created another PR for the deployment files - https://github.com/bobanetwork/boba/pull/234

**Review by InoMurko — APPROVED** [review]

**Comment by InoMurko** [comment]
@java-spaces should give a thumbs up in terms of language I think!

**Comment by java-spaces** [comment]
@Boyuan-Chen This commentary is great -- but I would make one adjustment. This does a great job describing what was solved, but it would be even better if it described why the change was needed in the first place. And then how that problem was solved with the changes made in the PR.

**Comment by boyuan-chen** [comment]
> @Boyuan-Chen This commentary is great -- but I would make one adjustment. This does a great job describing what was solved, but it would be even better if it described why the change was needed in the first place. And then how that problem was solved with the changes made in the PR.

Added

**Review by java-spaces — APPROVED** [review]

**Pull request merged**
