### PR TITLE
minor changes to monorepo dockerfile to facilitate building on mac si…

### PR DESCRIPTION
**Pull request by CAPtheorem**
The test for ARM does not seem to be working correctly - `grep -q` is not doing what we expect it to? Grep -i seems a partial fix, but the if () is still not executing properly.

Also added the missing `--platform linux/amd64` flag for Docker in case of Mac silicon

### CODE REVIEW

**Comment by InoMurko** [comment]
This isn't really working as expected. based on logs:
```
2022-03-23T03:59:01.3123908Z #7 4.320 Building for Mac (linux/amd64)
2022-03-23T03:59:01.3124256Z #7 4.320 /bin/sh: 1: [[: not found
```

it builds for mac on a ubuntu host.

**Comment by InoMurko** [comment]
on debian
 uname -a
Linux ip-172-31-5-5 5.10.0-12-cloud-arm64 #1 SMP Debian 5.10.103-1 (2022-03-07) aarch64 GNU/Linux:
```
inomurko@ip-172-31-5-5:~/opt/boba/ops$ docker-compose build builder
Building builder
Sending build context to Docker daemon  449.5MB
Step 1/41 : FROM node:16-buster-slim as node
 ---> d2dde0aca1e9
Step 2/41 : ARG TARGETPLATFORM
 ---> Using cache
 ---> 99c5c1c97041
Step 3/41 : RUN echo "Platform: $TARGETPLATFORM"
 ---> Running in f12afb361a3a
Platform: 
Removing intermediate container f12afb361a3a
 ---> 1eb6ffe93fd1
Step 4/41 : RUN if [[ "$TARGETPLATFORM" == "linux/amd64" ]] ; then           echo "Building for x86_64" ;           apt-get update -y && apt-get install -y git ;      else           echo "Building for Mac ($TARGETPLATFORM)" ;           apt-get update -y && apt-get install -y git python3 build-essential ;      fi
 ---> Running in 6e69493796d2
/bin/sh: 1: [[: not found
Building for Mac ()
```


```
inomurko@:~/opt/boba/ops$ docker-compose build builder
Building builder
Sending build context to Docker daemon  421.5MB
Step 1/44 : FROM node:16-buster-slim as node
 ---> d2dde0aca1e9
Step 2/44 : ARG TARGETPLATFORM
 ---> Running in 90a77408e15a
Removing intermediate container 90a77408e15a
 ---> 99c5c1c97041
Step 3/44 : ARG BUILDPLATFORM
 ---> Running in a2d9491089a1
Removing intermediate container a2d9491089a1
 ---> 63301954cb91
Step 4/44 : RUN echo "I am running on $BUILDPLATFORM, building for $TARGETPLATFORM"
 ---> Running in 6d9558e55396
I am running on , building for 
Removing intermediate container 6d9558e55396
 ---> fbb6dcbc49a2
Step 5/44 : ARG TARGETPLATFORM
 ---> Running in 408d32525fd8
Removing intermediate container 408d32525fd8
 ---> c5d767a8af70
Step 6/44 : RUN echo "Platform: $TARGETPLATFORM"
 ---> Running in 214c9e67249a
Platform: 
Removing intermediate container 214c9e67249a
 ---> 4baa90fcb196
Step 7/44 : RUN if [[ "$TARGETPLATFORM" == "linux/amd64" ]] ; then   echo "Building for x86_64" ;   apt-get update -y && apt-get install -y git ;   lse if [[ "$TARGETPLATFORM" == "linux/amd64" ]]   echo "Building for Mac ($TARGETPLATFORM)" ;   apt-get update -y && apt-get install -y git python3 build-essential ;   fi
 ---> Running in 2baf2fd85260
/bin/sh: 1: [[: not found
```

**Comment by CAPtheorem** [comment]
interesting - seems like `ARG TARGETPLATFORM` is not supported on debian?

**Comment by CAPtheorem** [comment]
Just changed to `BUILDPLATFORM` - what is that set to on your system @InoMurko?

**Comment by InoMurko** [comment]
```
Darwin Boyuans-MBP 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 x86_64

Darwin Inos-MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64

Linux ip-172-31-5-5 5.10.0-12-cloud-arm64 #1 SMP Debian 5.10.103-1 (2022-03-07) aarch64 GNU/Linux
```


but on debian aarch64 `buildplatform` is not defined, so I propose we stick with uname -a amd fix for sillicon:
```
RUN if echo "\"`uname -a`\"" | grep -q -E -i "(arm64|aarch)" ; then \
     apt-get update -y && apt-get install -y git python make gcc libudev-dev libusb-1.0-0-dev g++ pkg-config ; \
     else \
     apt-get update -y && apt-get install -y git; \
     fi
```

**Pull request merged**
