### PR TITLE
feat: add metaforra.com futuructa game into a project list

### PR DESCRIPTION
**Pull request by ablgmv**
## Overview

Added Futuructa game of the metaforra.com ecosystem into a project list.

## Changes

- Added project description to project.list.js
- Added logo futuructa.webp file to images/ecosystem directory

## Testing

You should run the project, go to /ecosystem path and see that Futuructa project has been successfully added to the project list. It has "gamefi" type so please be sure that GAMEFI category exists. We don't see this category on the current version of the BOBA website so maybe it should has been created before.

### CODE REVIEW

**Comment by ablgmv** [comment]
@wsdt Please take a look

**Comment by wsdt** [comment]
@souradeep-das do you know something about the `gamefi` category?

**Comment by wsdt** [comment]
please add `gamefi` to  `const typeOrder = [ 'defi', 'nft', 'bridge', 'wallet', 'tool', 'token' ]` on line 406.

Then it should work for my understanding. 

I think for now, maybe add it as second or third value in the array, but my assumption is that we might move Gamefi to the first tab since we want to double down on Gamefi. 

@sterswift thank you

**Comment by ablgmv** [comment]
> 

Ok @wsdt , so I'm gonna add it on the first place

**Comment by ablgmv** [comment]
@wsdt added gamefi to the typeOrder

**Review by wsdt — APPROVED** [review]
thx!

**Comment by wsdt** [comment]
@InoMurko @sk-enya please approve

**Comment by sk-enya** [comment]
@sterswift 
Can you please add `gamefi` to PROJECT_CAT 
`/containers/ecosystem/Ecosystem.js` at line 13 so it will be visible for the user to filter refer screenshot below.
Screenshot 2022-08-16 at 12 49 54 PM

**Review by sk-enya — CHANGES_REQUESTED** [review]
Please refer comment above for changes required.

**Comment by ablgmv** [comment]
> PROJECT_CAT

@sk-enya Done

**Review by sk-enya — APPROVED** [review]
LGTM

**Comment by wsdt** [comment]
@InoMurko seems to be stuck

**Review by InoMurko — APPROVED** [review]

**Pull request merged**
