### PR TITLE
Split TxSize flag for proposer and sequencer

### PR DESCRIPTION
**Pull request by boyuan-chen**
:clipboard: Add associated issues, tickets, docs URL here.

## Overview

Describe what your Pull Request is about in a few sentences.

To reduce gas cost on L1, we pick a large transaction size for both sequencer and proposer. However, the proposer might be panic due to the error `RLPTooLarge`. To solve this problem, we split `MaxL1TxSize` and `MinL1TxSize` for the proposer and sequencer. They can pick different values to meet our requirements.

## Changes

Describe your changes and implementation choices. More details make PRs easier to review.

- Change `MaxL1TxSize` and `MinL1TxSize` flags to `MaxSequencerL1TxSize`, `MinSequencerL1TxSize`, `MaxProposerL1TxSize` and `MinProposerL1TxSize`

## Testing

Describe how to test your new feature/bug fix and if possible, a step by step guide on how to demo this.

### CODE REVIEW

**Review by InoMurko — APPROVED** [review]

**Comment by InoMurko** [comment]
Test coverage would be nice. `Flags_test.go`

**Review by wsdt — APPROVED** [review]

**Comment by InoMurko** [comment]
do you want to add flags tests @Boyuan-Chen ?

**Comment by boyuan-chen** [comment]
> do you want to add flags tests @Boyuan-Chen ?

The existed flag tests have already checked all required and optional envs.

https://github.com/bobanetwork/boba/blob/7d53a2d2f14300054abe6de40fac0762a291bb12/go/batch-submitter/flags/flags_test.go#L12

**Comment by InoMurko** [comment]
I will close this since it seems to not be a priority.

**Pull request closed without merging**
