### PR TITLE
Update DiscretionaryExitFee contracts to testnets

### PR DESCRIPTION
**Pull request by boyuan-chen**
:clipboard: Add associated issues, tickets, docs URL here.

## Overview

Describe what your Pull Request is about in a few sentences.

Deployed DiscretionaryExitFee to testnets and registered all contracts to `Lib_AddressManager`.

### CODE REVIEW

**Review by souradeep-das — APPROVED** [review]

**Comment by sk-enya** [comment]
@souradeep-das @Boyuan-Chen 
Goerli:  Looks good.
https://testnet.bobascan.com/tx/0xc6ff5b02d26514e3121a4359f906020069edf30f5e7413de6b151dd27e82d718

Tested for 
BNBTestnets :  Looks good.
https://blockexplorer.testnet.bnb.boba.network/tx/0xc9b4cb5ccaa389d4395b555132154f8dcfb4785c923f81cbde4ed83200a829e1

BobaFuji : Looks good
https://blockexplorer.testnet.avax.boba.network/tx/0x67e7a0d14c1a500df2295a5eb75b8232f232e189305c722c5902c897ff006523


Seems failing when we have fee as ETH on goerli.

**Review by sk-enya — APPROVED** [review]

**Comment by souradeep-das** [comment]
unrelated, but there seems to be some logic which approve the DiscretionaryExitFee depending on a non eth token conditional. so when eth is passed boba tokens are not approved and the call fails https://github.com/bobanetwork/boba/blob/develop/packages/boba/gateway/src/services/networkService.js#L2062

On what context is the getExitCost() method used and is this impacted?

**Comment by wsdt** [comment]
ping, to get #940 merged too.

**Comment by souradeep-das** [comment]
@sk-enya when you have time, can we confirm all transactions through this DiscretionaryExitFee works without gateway changes?

**Pull request merged**
