### PR TITLE
[Gateway] : Remove airdrop page access from gateway

### PR DESCRIPTION
**Pull request by sk-enya**
:clipboard: Add associated issues, tickets, docs URL here.

## Overview

Remove Airdrop feature or page from Gateway.

## Changes

Describe your changes and implementation choices. More details make PRs easier to review.

- Removed airdrop from routes and footer navigation
- Removed airdrop function invocation on an interval from home as it's not needed anymore.

## Testing

Airdrop route and way to navigate to the airdrop is removed from the gateway.

### CODE REVIEW

**Review by InoMurko — APPROVED** [review]

**Review by boyuan-chen — APPROVED** [review]
Probably remove the airdrop page `containers/airdrop/Airdrop` too?

**Comment by sk-enya** [comment]
> Probably remove the airdrop page `containers/airdrop/Airdrop` too?

Okay, I kept it if we need it in future... anyways good to cleanup now only removing it.

**Comment by sk-enya** [comment]
@Boyuan-Chen can you please review it once again so I will get it merged!

**Review by boyuan-chen — APPROVED** [review]
Thank you!

**Pull request merged**
