### PR TITLE
Fix rate limiting of gateway

### PR DESCRIPTION
**Pull request by boyuan-chen**
:clipboard: Add associated issues, tickets, docs URL here.

## Overview

Describe what your Pull Request is about in a few sentences.

Serval places import `GasSwitcher.js`. If any of them changes, the `useEffect` will run again which causes a lot of unnecessary RPC requests and the IP address reaches the rate limiting.

## Changes

Describe your changes and implementation choices. More details make PRs easier to review.

- Remove `useEffect `

## Testing

Describe how to test your new feature/bug fix and if possible, a step by step guide on how to demo this.

### CODE REVIEW

**Comment by InoMurko** [comment]
good catch!

**Comment by InoMurko** [comment]
does this break anything?

**Review by InoMurko — APPROVED** [review]

**Comment by boyuan-chen** [comment]
> does this break anything?

Yes, it makes too many RPC calls and anyone who use the gateway on Boba Mainnet will be blocked due to the rate limiting. It's only for the develop branch and will not affect the v0.3.0 release.

**Review by sk-enya — APPROVED** [review]
Looks add same change in the patch fixes of sentry
https://github.com/bobanetwork/boba/pull/468

**Comment by boyuan-chen** [comment]
> Looks add same change in the patch fixes of sentry
> #468

Great!

**Pull request merged**
