### PR TITLE
Refactor earn page to function components

### LINKED ISSUE #615: [ Gateway ] : Refactor earn page from classical to functional
## Issue Type

```
[ x ] bug report
[ ] feature request
```

## Current Behavior

Even after setting up a connection with meta mask, `connect button with user prompt` takes time to disappear.

## Expected Behavior

Connect button should disappear as soon as the connection with the metamask is set up

## Steps to Reproduce

1.
2.
3.

## Suggested Fix

Refactoring the Earn page component with functions and hooks will solve the rendering issue.

### PR DESCRIPTION
**Pull request by boyuan-chen**
:clipboard: closed #615 

## Overview

Describe what your Pull Request is about in a few sentences.

Refactor the earn page from the old React component to function

## Changes

Describe your changes and implementation choices. More details make PRs easier to review.

- rewrite the rendering logic

## Testing

Describe how to test your new feature/bug fix and if possible, a step by step guide on how to demo this.

### CODE REVIEW

**Review by wsdt — APPROVED** [review]

**Review by sk-enya — COMMENTED** [review]
Awesome!
It would be good if we rename it to "earn" as in menu List we are referring component as **earn**

**Comment by boyuan-chen** [comment]
> Awesome!
> It would be good if we rename it to "earn" as in menu List we are referring component as **earn**

Ok! `farm` is renamed to `rename` everywhere

**Review by sk-enya — APPROVED** [review]

**Comment by sk-enya** [comment]
Add button to layer switcher as earlier it was just showing the two icons for l1 and l2 along with address of wallet. like top right corner so fixed to below one!

Screenshot 2023-03-09 at 12 03 13 PM

**Comment by sk-enya** [comment]
Earlier it was like
Screenshot 2023-03-09 at 12 04 42 PM

**Pull request merged**
