### PR TITLE
Add Avalanche L2 docs

### PR DESCRIPTION
**Pull request by boyuan-chen**
## Overview

Describe what your Pull Request is about in a few sentences.

- Add docs of Avalanche L2
- Update docs for running the boba node for different L2s
- Add Avalanche deployment files

## Changes

Describe your changes and implementation choices. More details make PRs easier to review.

- Update README
- Add Avalanche deployment files
- Update the boba node instructions

### CODE REVIEW

**Review by souradeep-das — COMMENTED** [review]
any reason we repeated deployment files on rinkeby/fuji ?

**Comment by boyuan-chen** [comment]
> any reason we repeated deployment files on rinkeby/fuji ?

My fault. I didn't notice that.

**Review by wsdt — APPROVED** [review]
à Souradeep, otherwise great!

**Review by trangtran-enya — APPROVED** [review]

**Review by souradeep-das — APPROVED** [review]
🚀

**Pull request merged**
