### PR TITLE
Wsdt/turing examples

### PR DESCRIPTION
**Pull request by wsdt**
## Overview

Moved old Turing examples into `boba_examples`, made each project self-contained and some related work.

## Changes

- Moved Turing examples from packages/ to boba_examples/.
- Made each project self-contained. 
- added some documentation
- fixed some minor issues
- other minor fixes regarding readability, etc.

## Testing

Test compiles otherwise no changes. 

Issue: #225

### CODE REVIEW

**Review by souradeep-das — APPROVED** [review]
this is great!!

**Comment by wsdt** [comment]
@InoMurko @Boyuan-Chen one review missing.

**Review by InoMurko — APPROVED** [review]

**Comment by wsdt** [comment]
thx! the CircleCI build seems to be failing for most branches in the last week. Do we know something about this? It's saying error 22 everywhere and even appeared in a branch after a ReadMe change, so can't be because of a code change.

**Comment by InoMurko** [comment]
> thx! the CircleCI build seems to be failing for most branches in the last week. Do we know something about this? It's saying error 22 everywhere and even appeared in a branch after a ReadMe change, so can't be because of a code change. 


Yeah the boba deployer is intermittent because of the DAO deployment timming thingy, right @souradeep-das ? I can do a very simple fix of restarting it when it happens.

**Comment by wsdt** [comment]
> > thx! the CircleCI build seems to be failing for most branches in the last week. Do we know something about this? It's saying error 22 everywhere and even appeared in a branch after a ReadMe change, so can't be because of a code change.
> 
> Yeah the boba deployer is intermittent because of the DAO deployment timming thingy, right @souradeep-das ? I can do a very simple fix of restarting it when it happens.

no worries, thanks!

**Comment by souradeep-das** [comment]
yeah, I think there is some timing disorder when its running on circle, I could try to tweak that test too, until the dao changes

**Pull request merged**
